name: deploy

on:
  push:
    branches: ['main']
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PULL_PRIVATE_REPO_GITHUB_TOKEN }}
      
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ~/pungbox-frontend
            git pull
            source ~/.nvm/nvm.sh
            nvm use 18
            pnpm install
            pnpm run build
            sudo kill -9 $(sudo lsof -t -i:80)
            nohup sudo pnpm run serve --port=80 --host </dev/null &>/dev/null &
            
